# Generated by Django 5.2.3 on 2025-06-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campeonato', models.CharField(max_length=100, verbose_name='Nombre del campeonato')),
                ('nombre_auspiciante', models.CharField(max_length=100, verbose_name='Nombre del auspiciante')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del equipo')),
                ('siglas', models.CharField(max_length=10, verbose_name='Siglas del equipo')),
                ('username_twitter', models.CharField(max_length=50, verbose_name='Usuario de Twitter')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField(verbose_name='Año de participación')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbolec.equipofutbol')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del jugador')),
                ('posicion_campo', models.CharField(choices=[('arquero', 'Arquero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], max_length=20, verbose_name='Posición')),
                ('numero_camiseta', models.PositiveIntegerField(verbose_name='Número de camiseta')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo mensual')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipofutbol')),
            ],
        ),
    ]
